In [1]:
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
import matplotlib.pyplot as plt
from PIL import Image
from scipy import ndimage
import matplotlib.image as mpimg
import cv2
import os
import glob
import pandas as pd
import numpy as np

Using TensorFlow backend.


# Creating dataset of available images

In [2]:
img_dir = "images" # Enter Directory of all images 
data_path = os.path.join(img_dir,'*g')
files = glob.glob(data_path)
images=[]

for i in range(1646):

    img = cv2.imread(files[1])
    print(img)
    images.append(img)
    

[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  ...
  [37 34 30]
  [40 37 33]
  [44 41 37]]]
[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  .

[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  ...
  [37 34 30]
  [40 37 33]
  [44 41 37]]]
[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  .

[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  ...
  [37 34 30]
  [40 37 33]
  [44 41 37]]]
[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  .

  [44 41 37]]]
[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  ...
  [37 34 30]
  [40 37 33]
  [44 41 37]]]
[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
 

[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  ...
  [37 34 30]
  [40 37 33]
  [44 41 37]]]
[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  .

[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  ...
  [37 34 30]
  [40 37 33]
  [44 41 37]]]
[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  .

[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  ...
  [37 34 30]
  [40 37 33]
  [44 41 37]]]
[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  .

[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  ...
  [37 34 30]
  [40 37 33]
  [44 41 37]]]
[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  .

[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  ...
  [37 34 30]
  [40 37 33]
  [44 41 37]]]
[[[24 29 30]
  [15 20 21]
  [14 18 19]
  ...
  [10 13 17]
  [ 9 12 16]
  [ 8 11 15]]

 [[20 25 26]
  [13 18 19]
  [12 16 17]
  ...
  [ 9 12 16]
  [ 7 10 14]
  [ 4  7 11]]

 [[15 23 23]
  [ 9 17 17]
  [10 15 16]
  ...
  [ 6  9 13]
  [ 6  9 13]
  [ 6  9 13]]

 ...

 [[78 75 70]
  [77 74 69]
  [78 75 70]
  ...
  [46 43 39]
  [44 41 37]
  [41 38 34]]

 [[76 73 68]
  [76 73 68]
  [77 74 69]
  ...
  [44 41 37]
  [44 41 37]
  [44 41 37]]

 [[81 78 73]
  [81 78 73]
  [83 80 75]
  .

In [3]:
images = np.array(images)

In [4]:
images.shape

(1646, 224, 224, 3)

In [5]:
labels_train = pd.read_csv('train.csv')
labels_test =  pd.read_csv('test.csv')
y =labels_train['emergency_or_not']

In [6]:
y.shape

(1646,)

In [7]:
X=images

# defining CNN 

In [48]:
classifier = Sequential()

In [49]:
classifier.add(Convolution2D(16,kernel_size = (3,3),input_shape=(224,224,3),activation='relu',strides=(1,1)))

In [50]:
classifier.add(MaxPooling2D(pool_size=(2, 2)))

In [51]:
classifier.add(Convolution2D(32, kernel_size = (3, 3), activation='relu',strides=(1,1)))

In [52]:
classifier.add(MaxPooling2D(pool_size=(2, 2)))

In [53]:
classifier.add(Convolution2D(32, kernel_size = (3, 3), activation='relu',strides=(1,1)))

In [54]:
classifier.add(MaxPooling2D(pool_size=(2, 2)))

In [55]:
# flattening layer

In [56]:
classifier.add(Flatten())

In [57]:
# dense layers

In [58]:
classifier.add(Dense(128, activation='relu'))

In [59]:
classifier.add(Dense(64,activation='relu'))

In [60]:
classifier.add(Dense(32,activation='relu'))

In [61]:
classifier.add(Dense(1,activation='sigmoid'))

In [62]:
classifier.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [66]:
from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='loss', patience=10)

# fitting data

In [67]:
classifier.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_7 (Conv2D)            (None, 222, 222, 16)      448       
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 111, 111, 16)      0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 109, 109, 32)      4640      
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, 54, 54, 32)        0         
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 52, 52, 32)        9248      
_________________________________________________________________
max_pooling2d_9 (MaxPooling2 (None, 26, 26, 32)        0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 21632)            

In [68]:
classifier.fit(X,y,epochs=50,batch_size=500,validation_split=0.2,callbacks=[early_stopping])

Train on 1316 samples, validate on 330 samples
Epoch 1/50
1316/1316 [==============================] - 15s 12ms/step - loss: 0.6820 - accuracy: 0.5775 - val_loss: 0.6694 - val_accuracy: 0.6212
Epoch 2/50
1316/1316 [==============================] - 18s 14ms/step - loss: 0.6814 - accuracy: 0.5775 - val_loss: 0.6676 - val_accuracy: 0.6212
Epoch 3/50
1316/1316 [==============================] - 21s 16ms/step - loss: 0.6811 - accuracy: 0.5775 - val_loss: 0.6673 - val_accuracy: 0.6212
Epoch 4/50
1316/1316 [==============================] - 22s 16ms/step - loss: 0.6811 - accuracy: 0.5775 - val_loss: 0.6671 - val_accuracy: 0.6212
Epoch 5/50
1316/1316 [==============================] - 20s 15ms/step - loss: 0.6815 - accuracy: 0.5775 - val_loss: 0.6684 - val_accuracy: 0.6212
Epoch 6/50
1316/1316 [==============================] - 20s 15ms/step - loss: 0.6813 - accuracy: 0.5775 - val_loss: 0.6672 - val_accuracy: 0.6212
Epoch 7/50
1316/1316 [==============================] - 21s 16ms/step - loss: